// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SherlockShop.Services.ProductAPI.DbContexts;

#nullable disable

namespace SherlockShop.Services.ProductAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230802082454_SeedProducts")]
    partial class SeedProducts
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SherlockShop.Services.ProductAPI.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("Image")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.HasKey("ProductId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            CategoryName = "Coat",
                            Description = "The greatest coat of Sherlock Holmes himself.",
                            Name = "Belstaff milford",
                            Price = 5000.0
                        },
                        new
                        {
                            ProductId = 2,
                            CategoryName = "Umbrella",
                            Description = "An umbrella that can protect not only from the rain.",
                            Name = "Mycroft's umbrella",
                            Price = 2999.0
                        },
                        new
                        {
                            ProductId = 3,
                            CategoryName = "Scarf",
                            Description = "Nothing personal - just a scarf.",
                            Name = "Sherlock's scarf",
                            Price = 400.0
                        },
                        new
                        {
                            ProductId = 4,
                            CategoryName = "Musical instrument",
                            Description = "How do you feel about the violin?",
                            Name = "Sherlock's Violin",
                            Price = 7777.0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
